### PR TITLE
Call flush before release to correctly catch errors.

### PR DESCRIPTION
**Pull request by ijiraq**
@NormanHill most of theses changes are cosmetic.  commit 11d0536 needs checking to see if I've done the correct stuff in moving the flush activities out of release and into a new flush method.

There are a few commits that deal with error handling.  Likely those are OK as is.

### CODE REVIEW

**Comment by NormanHill** [comment]
CadcCache.py:
line 100: Comment refers to parameter readOnly which has been renamed read_only
line 820: "FLushing" should be "Flushing" in the log message

**Comment by NormanHill** [comment]
Assuming that flush is only called once while a file is opened, then the 
refactoring looks ok.

Norm

**Comment by NormanHill** [comment]
There are a couple of worrying notes in the fuse/flush documentation:

============

NOTE: The flush() 
<http://fuse.sourceforge.net/doxygen/structfuse__operations.html#ad4ec9c309072a92dd82ddb20efa4ab14> 
method may be called more than once for each open() 
<http://fuse.sourceforge.net/doxygen/structfuse__operations.html#a14b98c3f7ab97cc2ef8f9b1d9dc0709d>. 
This happens if more than one file descriptor refers to an opened file 
due to dup(), dup2() or fork() calls. It is not possible to determine if 
a flush is final, so each flush should be treated equally. Multiple 
write-flush sequences are relatively rare, so this shouldn't be a problem.

Filesystems shouldn't assume that flush will always be called after some 
writes, or that if will be called at all.

========

What happens if flush is called more than once because of a dup/fork. It 
may be that the existing reference counting makes that work, but I'm not 
sure.

Does the last line mean that a file can be written and closed without 
calling flush?

Norm

**Comment by ijiraq** [comment]
Looks like a close without flush is possible (I've not seen this occur but the documentation says that's an allowed action)  so we need to add a flush call to close that checks first if the cache data is dirty.

**Pull request merged**
